[tool.poetry]
name = "langgraph-tutorials"
version = "0.1.0"
description = ""
authors = ["Yohei <y.meguro.2008@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "3.12.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
